import { InventoryItem } from "@/app/data_interfaces/inventory-item";

export const testInventoryList1: InventoryItem[] = [
    {
      fixedAssetId: 1,
      currentEmployeeId: 2,
      newEmployeeId: 3,
      currentLocationId: 4,
      newLocationId: 5,
    },
    {
      fixedAssetId: 6,
      currentEmployeeId: 7,
      newEmployeeId: 8,
      currentLocationId: 9,
      newLocationId: 10,
    },
    {
      fixedAssetId: 0,
      currentEmployeeId: 1,
      newEmployeeId: 2,
      currentLocationId: 3,
      newLocationId: 4,
    },
    {
      fixedAssetId: 5,
      currentEmployeeId: 6,
      newEmployeeId: 7,
      currentLocationId: 8,
      newLocationId: 9,
    },
    {
      fixedAssetId: 10,
      currentEmployeeId: 0,
      newEmployeeId: 1,
      currentLocationId: 2,
      newLocationId: 3,
    },
    {
      fixedAssetId: 2,
      currentEmployeeId: 3,
      newEmployeeId: 4,
      currentLocationId: 5,
      newLocationId: 6,
    },
    {
      fixedAssetId: 7,
      currentEmployeeId: 8,
      newEmployeeId: 9,
      currentLocationId: 10,
      newLocationId: 0,
    },
    {
      fixedAssetId: 3,
      currentEmployeeId: 4,
      newEmployeeId: 5,
      currentLocationId: 6,
      newLocationId: 7,
    },
    {
      fixedAssetId: 8,
      currentEmployeeId: 6,
      newEmployeeId: 6,
      currentLocationId: 0,
      newLocationId: 1,
    },
    {
      fixedAssetId: 4,
      currentEmployeeId: 5,
      newEmployeeId: 6,
      currentLocationId: 7,
      newLocationId: 8,
    },
    {
      fixedAssetId: 9,
      currentEmployeeId: 5,
      newEmployeeId: 5,
      currentLocationId: 2,
      newLocationId: 2,
    },
    {
      fixedAssetId: 5,
      currentEmployeeId: 6,
      newEmployeeId: 7,
      currentLocationId: 2,
      newLocationId: 2,
    }
  ];

  export const testInventoryList2: InventoryItem[] = [
    {
      fixedAssetId: 1,
      currentEmployeeId: 2,
      newEmployeeId: 2,
      currentLocationId: 4,
      newLocationId: 5,
    },
    {
      fixedAssetId: 6,
      currentEmployeeId: 7,
      newEmployeeId: 8,
      currentLocationId: 9,
      newLocationId: 9,
    },
    {
      fixedAssetId: 4,
      currentEmployeeId: 1,
      newEmployeeId: 1,
      currentLocationId: 3,
      newLocationId: 4,
    },
    {
      fixedAssetId: 5,
      currentEmployeeId: 6,
      newEmployeeId: 6,
      currentLocationId: 8,
      newLocationId: 8,
    },
    {
      fixedAssetId: 10,
      currentEmployeeId: 0,
      newEmployeeId: 1,
      currentLocationId: 2,
      newLocationId: 2,
    },
    {
      fixedAssetId: 2,
      currentEmployeeId: 3,
      newEmployeeId: 4,
      currentLocationId: 5,
      newLocationId: 5,
    },
    {
      fixedAssetId: 7,
      currentEmployeeId: 8,
      newEmployeeId: 8,
      currentLocationId: 10,
      newLocationId: 0,
    },
    {
      fixedAssetId: 3,
      currentEmployeeId: 4,
      newEmployeeId: 5,
      currentLocationId: 6,
      newLocationId: 6,
    },
    {
      fixedAssetId: 8,
      currentEmployeeId: 9,
      newEmployeeId: 10,
      currentLocationId: 0,
      newLocationId: 1,
    },
    {
      fixedAssetId: 4,
      currentEmployeeId: 5,
      newEmployeeId: 5,
      currentLocationId: 7,
      newLocationId: 8,
    },
    {
      fixedAssetId: 9,
      currentEmployeeId: 10,
      newEmployeeId: 0,
      currentLocationId: 1,
      newLocationId: 2,
    },
    {
      fixedAssetId: 5,
      currentEmployeeId: 6,
      newEmployeeId: 7,
      currentLocationId: 8,
      newLocationId: 9,
    }
  ];
  